### ISSUE TITLE
Show created datetime in the post list

### ISSUE THREAD

**Issue by o-gh** [BoostIO/boost-app-discussions#10]
Ideas
・display the date and time of created to the post list

Reasons
・When there is no title, look for from the date and time of created

---------------
改善案
・Post一覧に作成日時を表示してほしい。

理由
・タイトルを入力しなくても、作成日時からPostを探したいため。

ご検討ください。

**Comment by Rokt33r** [comment]
もし、タイトルを入力しなかったせいなら、
タイトル未入力の時に、勝手にタイトルを「Created at 2015/11/25 16:30」にしてあげるのはどう思いますか？

**Comment by o-gh** [comment]
はい、そのほうが良いです。
タイトルを考えるのがわずらわしいため。
勝手にタイトルが入ると便利です。

**Comment by Rokt33r** [comment]
次に反映されると思います！反映したらまた告知して閉じます！

**Comment by o-gh** [comment]
ありがとうございます
よろしくお願いいたします

**Comment by Rokt33r** [comment]
v0.4.3から反映されました！応えるのがちょっと遅くなりました！

**Comment by o-gh** [comment]
だいぶ便利になりました！ありがとうございます。
