### ISSUE TITLE
Wish list

### ISSUE THREAD

**Issue by Rokt33r** [BoostIO/boost-app-discussions#12]
Feel free to tell us what you want!
気軽になんでも要請してみてください！
마음껏 필요한게 있으면 알려주세요!

- [ ] Chrome plugin (by @two-hats)
- [ ] Mobile app (by @rokt33r)
- [ ] Syncing Gist(by @vforvova)
- [ ] Mathematical expression in markdown(by @ykicisk)
- [ ] ...

**Comment by vforvova** [comment]
Hi @Rokt33r! I use boost for my programming snippets. Boost saves each of them on local storage. But I think it will be very cool to sync it with GitHub Gists as remote store.

**Comment by Rokt33r** [comment]
@vforvova 
Actually we are going to add similar things this month.

- Importing from Gist
- Exporting to Gist

But, not syncing. This is because I thought it would be impossible due to the difference of formats between Boost and Gist.
(Gist has no tags. And, Boost has no filename and is not able to add multiple snippets.)

But, while considering your opinion, I've realized syncing Gist is possible as long as I add `Gist` mode as a syntax mode.

1. User selects Gist mode as a syntax.
2. Code editor is replaced with a form like Gist.
3. PROFIT

It's hard to tell syncing Gist is available in this month. I'll give a shot as soon as I can!

**Comment by vforvova** [comment]
@Rokt33r importing and exporting from/to Gist will be great feature. Even without syncing. Thank you!

**Comment by Rokt33r** [comment]
@vforvova 
You're welcome. I'll inform you when these things(importing/exporting/syncing) are available. :smiley_cat:

**Comment by hiroyuki-sato** [comment]
Ctrl-p(move-up) support.
Press Ctrl-p move cursor up on emacs  and Many OSX Cocoa app.
But Boost(electron) can't work it. 
It's very stressful.

It is my first criteria to choice editor. 😀

**Comment by Rokt33r** [comment]
@hiroyuki-sato Got it! That feature will be shipped on next patch.

**Comment by hiroyuki-sato** [comment]
👍

**Comment by ykicisk** [comment]
最近Boostを使い始めました、Finder windowの機能が便利なので愛用しています。
しばらく使ってみた中で感じた要望が、2点あります。

* Markdownにおける数式の対応

機械学習ライブラリなどのメモを取るとき、どうしても数式が書きたい場面があります。
Markdown parserの変更機能の追加を検討されているようなので、数式もパースできるparserのサポートを検討していただければ幸いです。

* Finder windowにおける部分コピー

Finder windowでは、全文のコピーしかできないため不便です。
範囲指定コピーやコードブロック単位コピー(Markdownのとき)ができると便利だと思います。

**Comment by Rokt33r** [comment]
@ykicisk 
### 1. Markdownにおける数式の対応

LatexかMathMLみたいなのがMarkdownにも使えてほしい話ですか？
個人的にもほしいですけど、これをした瞬間他のサービスとの互換性を失ってしまいますね。
一応、互換性において考慮している対策があります。他のアプリケーション用にExportをした時に、数式をSvgイメージに入れ替えるやり方です。たんにまだ手が空くのが年明けてからになりそうで、、、すべてが実装されたら2月ぐらいになりそうですね。

けど、一応の互換性を考えずに数式だけの追加はすぐできると思います。
問題は「どういう感じでMarkdown文法を拡張して数式を入れるのか」が一番むずかしいところだと思いますけど、
意見を言ってもらえるとすごくありがたいですね！たぶん、より早い対応ができるかと

### 2. Finder windowにおける部分コピー

すみません、範囲を指定してコピペができないのはバグです。(月曜日のUpdateに含めておきます。)
そして、Block単位でコピされるのはかなり面白いアイディアですね！

**Comment by ykicisk** [comment]
@Rokt33r 
### 1.Markdownにおける数式の対応
私の中ではMarkdownの拡張方法として、Markdown-here・Marxico・StackeditのようなLatex形式の数式とMarkdownを組み合わせた文法をイメージしています。
個人的には、「$数式$」と「$$数式$$」のサポートがあれば十分だと思います。

### 2.Finder windowにおける部分コピー
なるほど、バグだったのですね。
迅速な対応ありがとうござます。

**Comment by Rokt33r** [comment]
@hiroyuki-sato Ctrl+p to navigate up is available now(v0.4.6)
@ykicisk　今日2番目の件は反映されました。そして、数式は互換性なしで、とりあえず、MarkdownにLatex使える感じに来週か再来週ぐらいに入れれると思います。実装される次第に改めて通知します。

**Comment by hiroyuki-sato** [comment]
@Rokt33r 

Thanks!, Ctrl+p worked!!.

**Comment by hiroyuki-sato** [comment]
みなさん、日本語で書いているので日本語で

* 保存ボタンを押した時に編集のままになる機能が欲しいです。

どちらでも良いです。
  * 設定で保存時編集のままにしておく
  * 編集状態のまま保存する

こまめにセーブしているのですが、その度に編集を押すのは面倒

余談ですが、要望別にIssueを作った方がわかりやすいような..

**Comment by Rokt33r** [comment]
@hiroyuki-sato

#### 編集保存

自分もその問題すごく感じたんですけど、どうすればいいかわからなくて放置したんですね。
けど、@hiroyuki-satoの話を聞くと保存編集と編集を流すためのリセットボタンを用意しておいたらいい感がします！

現状Windows版の準備で来週頃に手が出せると思いますので、さっそく対応できるように頑張ります。

#### 要望において新しいIssueを出すことにおいての制限はないです。

ほかのIssueから出たIdeaであっても、みんなで知らせる必要があると思ったら自分が勝手にWishlistにも追加しておくので、自由に書いてもらえたらいいかと思います。

単に、Wishlistの存在のせいで新しいIssueを出さずにずっとコメントを加えていく形になった気がするので、後々Contribution guideみたいなものを作っておきます。ｗｗ

**Comment by hiroyuki-sato** [comment]
@Rokt33r 

まとめるとこんなのがいいと思います。

編集画面でCmd-sで保存は、プレビューに遷移せずに保存済みの状態とする

編集画面でESCを押した場合。
* 保存済みだったら、プレビューに移動
* 未保存だったら、確認画面を出す。変更を破棄するか？は、NOがデフォルト

編集中にESCを押すと確認画面がでますが、編集を破棄しますか？、現状YESがデフォルトですが、NOがデフォルトがいいですね。

**Comment by hiroyuki-sato** [comment]
@Rokt33r 

Shareボタンを押したら勝手にシェアされてしまったのですが、これどうやって消したらいいんでしょう？、全然Shareしたくない情報で急いで消したいのですが、記事を消してもShareされた情報が消せません。

Shareの機能は無効にする方法があると良いです。
Shareをする時はShareしますか？と確認画面を出して

**Comment by Rokt33r** [comment]
@hiroyuki-sato 上の編集関係の内容に関しては参考にしておきます！

Shareに関してはWishlistと無関係な部分もあるので、新しいIssueを出してもらいたいですね。
そして、Share事態を無効化にする機能はまだ待ってもらいたいです。現在チームで検証をしている部分であるので、まだ手が出せない感じですね。すみません。

一応、消したいデータに関しては、記事のURLを私のメール(fluke8259@gmail.com)に直接送ってもらえるとさっそく対応します！

**Comment by hiroyuki-sato** [comment]
Ctrl-pで上に動くようになったのはよいのですが、現在の表示領域が文書のまんなかぐらいの時に、Ctrl-pを押し続けると、スクロールバーが移動せずに、カーソルだけが上に移動します。
↑のようにスクロールバーも一緒に移動するようにして欲しいです。

**Comment by Rokt33r** [comment]
@hiroyuki-sato 
たぶん今週中に反映できるかと、
今日 https://en.wikipedia.org/wiki/Table_of_keyboard_shortcuts を見つけたので、このどおりにKey設定も全部合わせる予定です。

**Comment by hiroyuki-sato** [comment]
ありがとうございます。
可能であれば、Ctrl-k, Ctrl-yもあるといいですね。

[Mac OS X で使える Emacs スタイルのキー操作](https://www.facebook.com/notes/清野-克宏/mac-os-x-で使える-emacs-スタイルのキー操作/120880011324682/)

**Comment by Rokt33r** [comment]
@hiroyuki-sato 
参考にします！すごく助かりました！

**Comment by LukeXuan** [comment]
Please Let us adjust the font size.
While it looks perfectly on my laptop. It really hurts my eyes on my surface.

**Comment by Rokt33r** [comment]
@LukeXuan I'll ship it to next update. Wait a little while!

**Comment by ystkme** [comment]
インデントについて要望があります。

- 言語ごとのコーディングスタイルとして一般的なインデントの形式がある場合は、その値をデフォルトにしてほしいです。例えば、Rubyなら空白2つのインデント幅など。

- その上で、言語ごとにインデント幅を変えられるようにしてほしいです。

自動インデントが期待通りの幅でないことがあるため、毎回インデントを直す必要があってフラストレーションが溜まる、というのが要望の理由です。

**Comment by Rokt33r** [comment]
@ystkme 非常にわかります！今週のアップデート以内に実装できるようにしたいですね。早速対応できるように頑張ります。

**Comment by ccadieux** [comment]
* Support for images and file attachments. 
* Support for using the file system instead of localStorage.

**Comment by Rokt33r** [comment]
@ccadieux Boostnote will support them all! I'll make a new issue about that on this weekend!

**Comment by Waxo** [comment]
I'm really looking for the linux version. This tool seems great !

**Comment by Rokt33r** [comment]
@Waxo Thanks for your comment! We will support Ubuntu first!

**Comment by kyungtaek** [comment]
OSX 사용중이며 의견드립니다^^ (한글 코멘트는 처음인 것 같네요;)

* 시스템 시작시 자동실행 옵션이 있으면 어떨까 합니다. 
* 스토리지 경로를 커스텀할 수 있다던가, iCloud 또는 드롭박스를 지원하면 어떨까요? 몇몇 메모 또는 클립보드앱의 경우에는 드롭박스 경로에 스토리지를 지정할 수 있게 되어있어서 여러 컴퓨터에서의 동기화 이슈를 쉽게 해결하고 있습니다^^

마크다운 지원 너무 사랑스러워요! 
앞으로도 쭈욱 발전하시길 기원하겠습니다^^

**Comment by Rokt33r** [comment]
@kyungtaek 코멘트 감사합니다!

### 시스템 시작시 자동실행 옵션

자동실행옵션은 어플리케이션 내부에서 구현하고 싶진 않아요. 사용자 타겟자체가 일반인이 아닌 개발자라 System Preferences -> Users & Groups -> Login Items에서 로그인시 시작할 어플리케이션을 설정하는게 어렵지 않을꺼라 생각해요. 그리고 개발자같은 사람입장에서 암호를 다시 요구하거나 Allow/Disallow 다이얼로그를 꺼내는게 그다지 유쾌하지 않은 UX일거라... 앱 내부에서 이런걸 요구하게 하고 싶진 않네요... 아마 튜토리얼을 따로 만들어서 운영체제별 설정법을 알려주는게 더 좋지않을까 싶어요.

### 스토리지 경로

스토리지 경로는 완전하게 자유를 드릴 예정입니다. 포스트 하나당 하나의 파일로 만들것이고 신택스 모드에 적합한 확장자을 넣어줄 계획입니다. 이렇게하면 데이터가 전부 파일베이스로 관리되기때문에 따로 어플리케이션 내부에서 드롭박스나 구글드라이브에 로그인을 할 필요없이 파일을 그대로 엑세스가 가능하게 될거에요. 일반적인 코드 에디터처럼요!  그리고 완전히 Git으로 관리할 수 있게해서 Github나 Bitbucket의 저장소까지 클라우드로 사용하게 할 계획이에요!

### 맥앱스토어

앱스토어는 언젠가 런치할지도 모르겠는데 아직 잘 모르겠어요. 외부노출이 되는게 장점인 듯해 보이는데 다른 단점이 많으니 아직 꺼려지네요. 업데이트마다 심사가 필요하고 유료로 팔 계획도 없는 상태라... 

여튼 이상입니다. 아직 궁금하신것 있으시면 더 물으셔도 되고 이외의 내용도 괜찮아요!

**Comment by hiroyuki-sato** [comment]
プレビュー -> エディットに切り替わる操作をマウスで**できないように**したいです。(0.5から？)

Markdownモードで編集していて、テキストをコピーペーストしようとすると
画面がエディットモードに切り替わってしまってコピーしづらいです。
素早く選択するとプレビューモードのままでできるんですが、

エディットするとき、プレビューするときはボタンを押すので、
時間やマウスの操作で切り替わらない方が操作しやすいです。

**Comment by Rokt33r** [comment]
@hiroyuki-sato 
次のVersionに右クリックだけで変換できるOptionを追加する予定です！
キーボードでする場合はEscと`e`で切り替えできます。

現状はある程度マウスを長押しすると編集状態に入らないようになっています。(ドラグをするために)

UX的に検証がしたかったんで、少し申し訳ないです。
現状反応が半分にわかれていて次のような感じですね。

非常に使いやすくなった VS 勝手に変わるから面倒くさい

とりあえず、次のVersionに反映される予定で来週の月曜日にリリース予定です

**Comment by hiroyuki-sato** [comment]
v0.5.2を早速導入しました。
Switching Previewの説明ってどこかに記載されていますでしょうか？

左クリックで編集にしたくないので、When Right Clickingにしたのですが、
プレビュー時にeを押したり、エディット中にESCを押してプレビューに移動できなくなってしまいました。
右クリック(左クリックで編集をoffにしていても)ESC, eが使えるようにして欲しいです。

**Comment by Rokt33r** [comment]
@hiroyuki-sato 
それは自分も意図しなかったことですね。次に直しておきます。

そして、これからWish Listじゃなくて新しいIssueを作ってもらえませんか？
ここで、Wish Listのコメントが無駄に長くなるきがして、全部独立したIssue作ってもら痛いです。

**Comment by hiroyuki-sato** [comment]
了解しました。

**Comment by Rokt33r** [comment]
Close this issue due to its duplicated purpose. #16
