### ISSUE TITLE
CommonMark Support ?

### ISSUE THREAD

**Issue by mackoj** [BoostIO/boost-app-discussions#13]
Hi,

Do you plan to support http://commonmark.org in your app ?

Cheers,

**Comment by Rokt33r** [comment]
Of course! It would be available quite soon. :dancer:

**Comment by mackoj** [comment]
Great

**Comment by Rokt33r** [comment]
I've noticed a problem while checking the spec of CommonMark. There is a possibility of XSS attack because of HTML block. Therefore, I think I have to filter some tags(`script`, `style`) and attributes.(
What do you think about that?

**Comment by mackoj** [comment]
Does this respond to your question ?

**Comment by Rokt33r** [comment]
Thank you! I'll close this issue after I implement it! :dancers:

**Comment by Rokt33r** [comment]
Sorry to have kept you waiting. It will be shipped on this week!
And, this is my whitelist! #26
We can talk about it there.
