### ISSUE TITLE
Enable --disable-direct-write flag

### ISSUE THREAD

**Issue by Rokt33r** [BoostIO/boost-app-discussions#15]
If any problem on using windows app of Boostnote, add comment here!

**Comment by alemonmk** [comment]
Having a option to disable DirectWrite would be great for anyone using some fonts which require interference from program like MacType to look good.

**Comment by Rokt33r** [comment]
@alemonmk
It seems to be possible.
https://github.com/atom/electron/blob/master/docs/api/browser-window.md
I'll ship it to next update! :yum:

**Comment by Rokt33r** [comment]
@alemonmk It works!

Disable direct write
<img width="960" alt="disable direct write" src="https://cloud.githubusercontent.com/assets/5865853/12216026/e7a25286-b717-11e5-87da-d0189b3e082c.png">

Enable direct write
<img width="960" alt="normal" src="https://cloud.githubusercontent.com/assets/5865853/12216022/ced3a71e-b717-11e5-8807-e8a6ab115f6f.png">

It will be configurable here!
<img width="960" alt="2016-01-09 15" src="https://cloud.githubusercontent.com/assets/5865853/12216042/218c989e-b718-11e5-9f30-46143a239af4.png">

**Comment by eladkarako** [comment]
<h3>try <code>--disable-directwrite-for-ui</code> <sub><a href="http://icompile.eladkarako.com/disable-direct-write-alternative-for-chrome/" title="#disable-direct-write Alternative For Google Chrome"><em>source</em></a></sub></h3>
