### ISSUE TITLE
install failed. installer for windows

### ISSUE THREAD

**Issue by cactus171** [BoostIO/boost-app-discussions#20]
インストールこけました。
よろしくお願いします。
OSはwin7です。

[SquirrelSetup.zip](https://github.com/BoostIO/boost-app-discussions/files/72076/SquirrelSetup.zip)

--------
@roadman171

**Comment by Rokt33r** [comment]
すでに設置されていると思います。
Tray確認してみましたか？Boostnoteがすでに起動中であるけど、再インストールしようとするときに出るエラーだと思います。

このアプリはメインウィンドウを消しても検索機能のために全部終了はされないです。
再インストールをしたかったら右下の方に時間があるところに右上の矢印Boostnoteのアイコンを探してみてください。
それを選択すると実行されているアプリを終了するメニューとかメインウィンドウを改めて呼び出すメニューが出ると思います。

Tray iconが何なのか知らなかったら下のスクショを参考してください！
![system-tray-windows-7-move](https://cloud.githubusercontent.com/assets/5865853/12001831/9fd7b0de-ab34-11e5-90ba-02c6b1efe461.png)

**Comment by Rokt33r** [comment]
Closed: due to no responding

**Comment by cactus171** [comment]
返信ありがとうございます。
Trayを確認しましたがそれらしいものは見当たりませんでした。
他に試しておくべきことはありますか？

よろしくお願いします。

**Comment by Rokt33r** [comment]
Ctrl + Alt + Deleteから実行中のプロセスを確認してもらいますうか？
Boostnoteが実行されているのかを確実に確認したいです。

そして、コントロールパネルも開いて、Programs and FeaturesからすでにBoostnoteというアプリが設置されているのかを確認してもらいたいです。

とりあえず、たぶん何かの原因により、C:\Users\現在のユーザ名\AppData\Local\boostにInstallerが設置ファイルを入れることができない時にその問題が発生すると思います。

**Comment by cactus171** [comment]
ともに確認してみましたがBoostnoteは設置されていませんでした。
念のためC:\Users\現在のユーザ名\AppData\Local\boostを確認してみたところ以下のフォルダ、ファイルが見つかりました。
・app-0.5.0
・packages
・Update.exe

ちなみにOSは32bit版なのですがこれが原因ということは考えられますでしょうか。

**Comment by Rokt33r** [comment]
あ、、 32bitにはまだ対応していないですね。
すみません、完全に誤解しました。

とりあえず、32bitはまだですね、、
たぶん、Github repoなどのところまで完成出来て正式版として出せる段階で対応していくと思います。
適当な目安としては来年の春からかなと思います。
