### ISSUE TITLE
Strange render with Chinese charactors

### ISSUE THREAD

**Issue by LukeXuan** [BoostIO/boost-app-discussions#23]
![image](https://cloud.githubusercontent.com/assets/3363954/12085768/739482c8-b2fe-11e5-8408-55df25a96a3b.png)
As is shown in the image, some of the characters have heavier weight over others. I think it might be caused by lack of fonts.

p.s. Is there any way for community contribution? ex. add Chinese supports or add some features that a severly demanded.

**Comment by Rokt33r** [comment]
I think this is because I forgot adding `sans-serif` to `font-family`.
Also, I'll make it configurable on next update.(next update will be shipped on this week)

Btw, community contribution.. In fact, our team is considering make this app as open source now.
But it would be March as soon as possible, I think.

Till then, creating an issue would be thankful. I'll do my best to catch up.

**Comment by Rokt33r** [comment]
![screen shot 2016-01-04 at 7 13 26](https://cloud.githubusercontent.com/assets/5865853/12087555/5690e3ba-b317-11e5-85ef-9fc90f1345b0.png)
Adding `sans-serif` seems to work!

**Comment by LukeXuan** [comment]
re: @Rokt33r wow It great!
Looking forward to the next release and the open source date.

**Comment by Rokt33r** [comment]
It is so glad to hear that! I'll do my best! :tada:
Btw, I'll close this issue after deploy the new release.

**Comment by Rokt33r** [comment]
It will be totally configurable!
<img width="960" alt="2016-01-09 15" src="https://cloud.githubusercontent.com/assets/5865853/12216057/8aedac56-b718-11e5-9b3f-38390d3a64c1.png">

Also, You can set font-family like this, `Lato, Microsoft YaHei, sans-serif`, as same as CSS.

The updated app will be released on next Monday #28

**Comment by Rokt33r** [comment]
Although I updated, It doesn't seems to be fixed on Windows. I'm terribly sorry.. I'd checked only on OS X.
I'll set Microsoft Yehei as default.

**Comment by Rokt33r** [comment]
Fixed! #35
