### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by Brunosilva84** [BoostIO/boost-app-discussions#24]
Hi, I have a dobts about this app, if is possible we use github and Boostnote, my idea is using my notes in 2 computers. 

Or one repository , where I can send my notes and get another computer.

Tnks

**Comment by Rokt33r** [comment]
Sorry, I cannot understand what you want to ask exactly.

Btw, Using Github repo is not possible yet. It will be shipped after Feb, 2016. Check #18.
If this answer is not helpful, feel free to ask again.

**Comment by Brunosilva84** [comment]
Rs. For example I have my annotations in my work computer and I would like have this same annotations in my another computer in the house.

**Comment by Rokt33r** [comment]
This is my plan.

1. A user commits some changes.
2. Boostnote client pushes to remote repo(Github) by the user's Git client.
3. Github repo triggers Boostnote server by Web hook
4. Boostnote server publishes the event by Web socket
5. All subscribed Boostnote clients pull the committed changes. (If there are some conflicts, Boostnote client will resolves it automatically.)

**Comment by Rokt33r** [comment]
We can talk about it more here #29! Don't hesitate to ask!
