### ISSUE TITLE
Inline HTML for Markdown does not work

### ISSUE THREAD

**Issue by maki-chan** [BoostIO/boost-app-discussions#25]
Whenever I try to put HTML tags into a Markdown document, it doesn't recognize the HTML tags and prints them out as text instead.

According to the official Markdown documentation, inline HTML should be possible.

**Comment by Rokt33r** [comment]
It was intended. But, we will support [CommonMark](http://commonmark.org/)(and Latex block by [Katex](https://github.com/Khan/KaTeX)) on next update.(will be shipped on this week)

If you doesn't mean CommonMark, could you give me a link of the specification of the official Markdown?

**Comment by maki-chan** [comment]
The official documentation can be found here: https://daringfireball.net/projects/markdown/

**Comment by Rokt33r** [comment]
Thank you for sharing the link. It will be shipped soon.
![screen shot 2016-01-05 at 11 57 28](https://cloud.githubusercontent.com/assets/5865853/12118183/60b21bb0-b408-11e5-9f5f-c6b6fa285240.png)
<img width="1440" alt="screen shot 2016-01-05 at 11 57 24" src="https://cloud.githubusercontent.com/assets/5865853/12118184/6209d444-b408-11e5-9165-8105a9a22ee6.png">

**Comment by Rokt33r** [comment]
Ah, I forgot to add <u> tag to whitelist of HTML preview. The release version would be fine.

**Comment by Rokt33r** [comment]
#26 We can talk here if you want some more features related in Markdown parser
