### ISSUE TITLE
Improving escaping

### ISSUE THREAD

**Issue by acadet** [BoostIO/boost-app-discussions#27]
I entered this as a new folder name: `Just you <3`.

However, I cannot neither select this new folder or add a new post in it. I think, as your app is based on JS, the arrow is wrongly escaped or not escaped at all.

**Comment by Rokt33r** [comment]
Thank you so much for reporting it! In fact, spaces in folder name must be replaced with `_`.
But, I've just found I forgot to adding `g` flag to my replace method. Therefore, the second space is not replaced.

```js
newFolder.name = newFolder.name.trim().replace(/\s/, '_')

newFolder.name = newFolder.name.trim().replace(/\s/g, '_')
```

Anyway, It is fixed now and will be shipped the update on this week!

**Comment by acadet** [comment]
Thanks @Rokt33r!
