### ISSUE TITLE
'Click to Edit' is not working well

### ISSUE THREAD

**Issue by alemonmk** [BoostIO/boost-app-discussions#30]
Great work on the 0.5.1 release!

However, I don't think the 'Click to Edit' is working well.

- Now I can't select texts as it jumps into edit mode after releasing <kbd>RMB</kbd> and lose my selection;
- Yet selecting some then go back to selecting none without releasing <kbd>RMB</kbd> doesn't trigger the switch;
- Clicking on selected texts in edit mode switch to preview mode, then back to edit mode after releasing <kbd>RMB</kbd> (though not really annoying);
- We lose context menu in edit mode but we can do a quick preview by right clicking. I would say this is a feature ;)

---

PS: What preview fonts do you use? Any CJK font I use still looks like crap even with DirectWrite off.
PS2: Maybe I should not be bothering you with this font issue anymore and wait till Boost get open sourced then try hacking it myself. Webkit has a very long history with font rendering :/

**Comment by Rokt33r** [comment]
I'm terribly sorry! I forgot to check right click behaviour. I will fix it on next update.

About font, it's not bothering me at all. And, I set sans-serif as a default font. It's fine to me because I dont use mactype.

Btw, we have 2 options. I think we should take both.

1. You need to teach me how to reproduce your situation. I don't know how to install MacType and which font you want to use.
2. You can make an example app for me. Boostnote is made on top of Electron.

If these are possible, we can fix this problem much faster!

**Comment by Rokt33r** [comment]
Quick preview with right click wasn't an intended feature. but I realized It is quite cool! It will be an official feature! :+1:

**Comment by alemonmk** [comment]
This font rendering problem deserves another issue, I will create one.

About this 'Click to edit' problem, I would recommend bring back the edit button, since double <kbd>LMB</kbd>s and triple <kbd>LMB</kbd>s selects texts with different ranges, and single <kbd>LMB</kbd> are used to focus on a window (and I like doing <kbd>LMB</kbd>s to track my focus while reading :P).

**Comment by Rokt33r** [comment]
How about making right click to toggle preview/edit available only? We have no plan now to add any context menu on preview and code editor.
Of course, bringing back edit button is also a valid option.

**Comment by alemonmk** [comment]
I would suggest restricting this <kbd>RMB</kbd> behavior in edit mode only. I don't want a misclick bring me to the source. Beside we still have the <kbd>e</kbd> hotkey.
Of course I don't know about others, this needs more opinions. :)

**Comment by Rokt33r** [comment]
I talked my team just now. I think we will provide 2 options both.

- Edit on focus(right click is disabled on preview mode, but it is available on edit mode for instant preview)
- Toggle Edit/Preview on right click.

> It may change if there are some other opinions.

**Comment by Rokt33r** [comment]
Fixed! #35
