### ISSUE TITLE
Font rendering issues

### ISSUE THREAD

**Issue by alemonmk** [BoostIO/boost-app-discussions#31]
This issue separating the discussion from #30.

My environment:
- Windows 7 SP1 x64
- DPI 100%
- [MacType 1.2012.1022.0](https://code.google.com/p/mactype/downloads/detail?name=MacTypeInstaller_2012_1022_0.exe&can=1&q=)
  - Profile: XMac.LCD.Default
- Fonts: [XHei Believe](http://rmntn.net/tmp/XHei.TTC) & [Hiragino Sans CNS W3](http://rmntn.net/tmp/HiraginoSansCNSW3.otf)

Here's some picture testing different settings, I'm giving link since pics are huge:
http://imgur.com/a/P58wC

[Here's some workaround for Chrome](http://s.jkunblog.com/article/155154584.html), I don't know how many applies here.

[Also a post probably related.](http://maxvoltar.com/archive/-webkit-font-smoothing)

I will try making an Electron app for experiments, but this can take a few days.

**Comment by Rokt33r** [comment]
I'll also try it on my old laptop. Thank you for cooperation!

**Comment by Rokt33r** [comment]
https://github.com/atom/electron/blob/master/docs/api/browser-window.md

I've just found `directWrite` of Electron. I'll send an example app to you on Sunday evening.

**Comment by Rokt33r** [comment]
https://github.com/Rokt33r/direct-write-test

Check this repo. I did't check it on Windows 7 yet.  I'll do it tomorrow after I get back from school.

**Comment by alemonmk** [comment]
Oops, this font issue is gone when I run it directly on my laptop instead via Remote Desktop. I guess this is an non-issue that is brought by myself, to myself.
So I'm closing this, thank you. :+1:

**Comment by Rokt33r** [comment]
You're welcome! :grin:
