### ISSUE TITLE
Windows10でインストール時にSmartScreen警告が出ました

### ISSUE THREAD

**Issue by kijtra** [BoostIO/boost-app-discussions#33]
Windows10 Homeです。
インストール時に以下の警告が出たので、念のため報告します。

![2016-01-14_093021](https://cloud.githubusercontent.com/assets/622304/12312349/116c1bbe-baa2-11e5-8db2-9c0f42be0840.png)

Windows10インストール時からのデフォルト設定（SmartScreenがON）ですので、他の方も出ているかもしれません。
「実行」してインストール自体は問題ありませんでした。

**Comment by Rokt33r** [comment]
EV Authenticode certificatesを買っていないからですね。
正直な話をすると、EVは高くて普通の認証書を使っています。

たぶん、アプリが商用のアプリにする予定であれば買うと思いますけど、Opensource化するつもりなので、しばらく普通の認証書を使い続けると思います。

面倒をかけてすみません。
