### ISSUE TITLE
KaTeX Bugs

### ISSUE THREAD

**Issue by ykicisk** [BoostIO/boost-app-discussions#36]
Boostnote v0.5.1において、特定の数式のパースに失敗します。

Markdown
```
$$a$$b$$c$$

$$\mathbf{a}$$
b
$$c$$

$$\mathbf{a}$$b$$c$$

```

結果
<img width="495" alt="2016-01-16 11 59 13" src="https://cloud.githubusercontent.com/assets/10989248/12370091/a37b7dfe-bc48-11e5-8695-498afa9b9f47.png">

**Comment by ykicisk** [comment]
もう一つバグを発見しました。
&のエスケープの問題かと思います。

Markdown
```
$$$
\begin{pmatrix}
a & b \\
c & d
\end{pmatrix}
$$$
```

結果

![2016-01-16 13 53 06](https://cloud.githubusercontent.com/assets/10989248/12370554/8096c34c-bc58-11e5-818b-77c8982a3f78.png)

**Comment by ykicisk** [comment]
更にもう一つバグを発見しました。

Markdown
```
$$a$$

$$a $$

$$ a$$
```

結果
![2016-01-16 14 32 27](https://cloud.githubusercontent.com/assets/10989248/12370700/009303bc-bc5e-11e5-952f-80fb50632c44.png)

**Comment by Rokt33r** [comment]
報告ありがとうございます！
たぶん、月曜のアップデートには間に合わないと思いますけど、今から手を出してみます。

**Comment by Rokt33r** [comment]
2番目のEscape問題は来週月曜日のアップデートに反映されると思います！

**Comment by Rokt33r** [comment]
2番目は治りました。#35

残り２つの問題も解決できる次第に告知します！:grin:

**Comment by Rokt33r** [comment]
3番目はGithubのMd parserを考えるとなおさなくていいと思います

~~取り消し線が適用されない ~~

~~取り消し線が適用される~~


```
~~取り消し線が適用されない ~~

~~取り消し線が適用される~~
```

**Comment by Rokt33r** [comment]
1の場合は自分で直してみようといろいろと触ってみましたが、Markdown-it-math packageの製作者に聞いて解決する形になると思います。

かなりTokenizingのやり方が複雑すぎて簡単ではないですね。遅れていてすみません。

とりあえず、このIssueでかいけつしようと思っていて、解決できる次第にアプリに反映します。
runarberg/markdown-it-math#14

では、このIssueは一応閉じておいて何か変わる次第にまた開いて告知します。
