### ISSUE TITLE
Finder[shift+ctrl+tab] doesn't working

### ISSUE THREAD

**Issue by tomothumb** [BoostIO/boost-app-discussions#37]
Section 3 on "About Boost" readme, [Shift +ctrl+tab press buttons at same time. Then, the window will show up for search Boost contents that instant.]
but it doesn't work.

Instead, I found Hotkey on Setting->Preferences.
Default Toggle Finder(popup) was [Cmd + alt + s]
When i put [Cmd + alt + s], finder will open properly.

I think this readme should be updated.

**Comment by Rokt33r** [comment]
Sorry about that! It will be fixed soon.

**Comment by Rokt33r** [comment]
Fixed!
