### ISSUE TITLE
Ctrl-y support on OSX

### ISSUE THREAD

**Issue by hiroyuki-sato** [BoostIO/boost-app-discussions#38]
See also: https://github.com/BoostIO/boost-app-discussions/issues/21

**Comment by Rokt33r** [comment]
It will be shipped to v0.5.3. :grin:

**Comment by Rokt33r** [comment]
Sorry, this will be shipped to v0.5.4.
In fact, I've already finished it, but I found a minor bug in there. So it will be shipped on next Monday!

**Comment by hiroyuki-sato** [comment]
👍

**Comment by Rokt33r** [comment]
Ready to ship! :package:
