### ISSUE TITLE
v0.5.2 Edit ``e`` key does not work on Preview mode with When Right Clicking mode.

### ISSUE THREAD

**Issue by hiroyuki-sato** [BoostIO/boost-app-discussions#39]
左クリックで編集にしたくないので、When Right Clickingにしたのですが、
プレビュー時にeを押したり、エディット中にESCを押してプレビューに移動できなくなってしまいました。
右クリック(左クリックで編集をoffにしていても)ESC, eが使えるようにして欲しいです。

**Comment by Rokt33r** [comment]
ありがとうございます！Right clickの時もESCが使えるようにする予定だったので、これはバグです。
次のアップデート(来週の月曜)に直します！

**Comment by Rokt33r** [comment]
Fixed. #40

**Comment by hiroyuki-sato** [comment]
v0.5.3. It worked!!
Thanks!
