### ISSUE TITLE
Strange Hotkey form's behavior

### ISSUE THREAD

**Issue by yoshitakame** [BoostIO/boost-app-discussions#41]
On OSX, Boostnote version 0.5.2.

As the GIF shows, its reaction(success / error message) is against expectation and actual behaviour. I think these all should be success.

- Leave them both empty => error (but actually works)
- Add "Toggle Main" a value and leave the other empty => success
- Add "Toggle Finder" a value and leave the other empty => error (but actually works)

[![https://gyazo.com/bb1fe57ec10598cce245448ece64c99d](https://i.gyazo.com/bb1fe57ec10598cce245448ece64c99d.gif)](https://gyazo.com/bb1fe57ec10598cce245448ece64c99d)

**Comment by Rokt33r** [comment]
わかりました！これ以外も少し致命的なバグが見つけたんで、明日修正版をUpdateします。

一応、エラーが出てはいますけど、無視していいかなと思います。

**Comment by Rokt33r** [comment]
Fixed. #40
