### ISSUE TITLE
I would like to delete shared content.

### ISSUE THREAD

**Issue by hiroyuki-sato** [BoostIO/boost-app-discussions#43]
v0.5.2

When I click ``Share via public URL`` button, it share on b00st.io site.
But I can't delete it. 

I would like to delete those contents by myself. 
ex) https://b00st.io/shared/5c3fba790315b775add5bccd762498318e1a1cae
(This is test so you don't delete it)

I already wrote this request on Dec 17 2015
https://github.com/BoostIO/boost-app-discussions/issues/12#issuecomment-165339107

I'm really looking forward to implementing this feature.

I know this feature already improved from previous version. :-)

**Comment by Rokt33r** [comment]
最初の計画はこのアプリケーションにログインして貰う予定でしたが、
今はそのプラン自体が完全になくなりました。

なので、現状の計画的にはSharedがなくなって、それを全部Gistに任す形に変わると思います。
もう少し待ってもらいたいです！

**Comment by hiroyuki-sato** [comment]
👍
As far as I can, I write issues in English for others.
ie. I can't read Korean😅, but I would like to know about their issues. 😀

**Comment by Rokt33r** [comment]
I'll create a new issue in English about Sharing.

Btw, the past issue written in Korean is not so important.
I was requested three features.
- Auto-start on boot
- Customization of storage. (Changing storage path, iCloud/Dropbox support)
- Launch Boostnote to Mac App store

But, I rejected 1st and 3rd request.
Setting an app to auto-start is easy. And, I think it would be annoying many users if I provide it as a feature. I don't want to force people to use my app.
Launching MAS is quite attractive. But, this app still has tons of things to be done. If this app is launched, every debugging process would take over 2 weeks.

**Comment by hiroyuki-sato** [comment]
Thank you for translating. Honestly, I used Google Translate. 😀

**Comment by Rokt33r** [comment]
You're welcome! :tada:
