### ISSUE TITLE
v0.5.3 "e" button does not work if I click an article.

### ISSUE THREAD

**Issue by hiroyuki-sato** [BoostIO/boost-app-discussions#44]
v0.5.3
Switching Preview: When Right Clicking mode.

Step

1. select article
2. left click in article.
3. press ``e`` button.

Without Step2, ``e`` work properly. 

same article in Japanese. 

手順

1. Markdown記事を選択します。
2. 記事内をどこでも良いのでクリックします。
3. ``e``ボタンを押します。

手順2がないと、``e``は正常に動作します。

**Comment by Rokt33r** [comment]
It is intended actually.
Keys without combination, such as `a`, `e`, `d` and `t`, must be scoped to prevent interrupting other actions.
I, therefore, set these keys are available only when Article List is focused.

So, It would work like below.

1. select article
2. left click in article.
3. **press esc**(focus Article List)
4. press e button.

**Comment by hiroyuki-sato** [comment]
OK. Thanks.
``ESC`` and ``e`` worked. 
Please write about this behavior in operation guide.

**Comment by Rokt33r** [comment]
Of course! :dancer: I'll add more description to #21.
But, the tutorial in app will be updated quite later due to new big UI changes is coming(Folder based storage/Git)
