### ISSUE TITLE
v0.5.3 Ctrl-e behavior on OSX

### ISSUE THREAD

**Issue by hiroyuki-sato** [BoostIO/boost-app-discussions#45]
[Reference](https://github.com/BoostIO/boost-app-discussions/issues/21)

Go to end of line. Ctrl + e

It does not work properly if the text  longer than window size.

in Japanese

ウインドウサイズに収まらないような長いテキストの場合、
Ctrl - eが期待する動作になりません。

次のように行がラップしている場合

```
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
bbbb
```

Ctrl-eを押すとここに動いて欲しいのですが
```
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
bbbb
   ^
```

ここに移動してしまいます。

```
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                                              ^
bbbb
```

**Comment by Rokt33r** [comment]
I'll check it.

Btw, I've realized recently that many Emacs features in Ace Editor doesn't work well.
So, I'm considering to import Atom's text editor and customize it somewhen. (But, it seems to be hard.. because atom is written in CoffeeScript)

**Comment by Rokt33r** [comment]
Ready to ship!
