### ISSUE TITLE
v0.5.3 Code block rendering GitHub Flavored Markdown.

### ISSUE THREAD

**Issue by hiroyuki-sato** [BoostIO/boost-app-discussions#46]
v0.5.3

It it possible to render same format Boost and Gist(GitHub)?

Source (Please replace single quote to backquote).

```
'''
hoge <--- hoge
'''
```

render text on gist.github.com
https://gist.github.com/hiroyuki-sato/9d394142a539ce5782bc

GitHub 

```
hoge <--- hoge
```

Boostnote

```
hoge
```

**Comment by Rokt33r** [comment]
This is a bug! #32 HTML inside Code block seems to be sanitized. I'll fix it now.

**Comment by Rokt33r** [comment]
<img width="197" alt="screen shot 2016-01-21 at 5 23 58" src="https://cloud.githubusercontent.com/assets/5865853/12462003/38340aa6-bfff-11e5-890b-4d1cce3cbb43.png">
<img width="238" alt="screen shot 2016-01-21 at 5 24 04" src="https://cloud.githubusercontent.com/assets/5865853/12462002/38331484-bfff-11e5-8d20-32854dc5ec03.png">

It will be updated on next Monday :+1:
