### ISSUE TITLE
v0.5.4 emacs keybinding.

### ISSUE THREAD

**Issue by hiroyuki-sato** [BoostIO/boost-app-discussions#51]
Ctrl-y worked Thanks.

But The following keybindings don't work correctly.

* Ctrl-p : Previous line. 0.5.3 worked.  😫
* Ctrl-a : Sorry I forgot to request at previous time (Ctrl-y request).

It is better to work like Ctrl-y.

Following wrapped line.  pos ^
```
aaaaaaaaaaaaaaaaaaa
bbb
   ^
```

Current

```
aaaaaaaaaaaaaaaaaaa
bbb
^
```

Request.

```
aaaaaaaaaaaaaaaaaaa
^
bbb
```

**Comment by Rokt33r** [comment]
Thank you for reporting! I'll fix it soon!

**Comment by Rokt33r** [comment]
I fixed both of them shipped to the next release. It will be published afternoon of tomorrow(GMT+9, Tokyo).
You can check it here. https://trello.com/b/wJlinZJx/boostnote-todo-list

**Comment by Rokt33r** [comment]
Done!

**Comment by hiroyuki-sato** [comment]
Worked Good!. Thanks!
