### ISSUE TITLE
BUG - Caret binding some of text while you choose it with mouse

### ISSUE THREAD

**Issue by FlickTheManual** [BoostIO/boost-app-discussions#53]
Hello;
Well, first,  great work dude, you rock!

But I've some little bug in the editor while I click in text;
It take all the text from carret initial place to your clicking stand.

![bootsnote_carret](https://cloud.githubusercontent.com/assets/2384206/12700223/c7f17d4e-c7f3-11e5-906f-948e98860c2a.PNG)

You'll see all the text selected; that is little annoying...

Good luck for rest.

**Comment by Rokt33r** [comment]
Sorry for late answer!! My semester exams are just finished today!!
This bug is reported! I'll fix it soon. Before fixing, you can deal with that bug by refreshing app(OSX Cmd+R / Ctrl+R)

**Comment by FlickTheManual** [comment]
What a great!!! Soon you've got it :D
Okay, sorry for duplicate it.
I try you're solution, thanx

*Matthieu GURAK*
tel: 06 92 491 170
@: matthieu.gurak@gmail.com

2016-02-04 14:01 GMT+04:00 Dick Choi <notifications@github.com>:
