### ISSUE TITLE
Cloud synchronization

### ISSUE THREAD

**Issue by nohe427** [BoostIO/boost-app-discussions#55]
Offer an option to synchronize notes between machines.

**Comment by Rokt33r** [comment]
I'm developing it now! Sorry for making you wait. :cry:

**Comment by nohe427** [comment]
Its all good.  Where are the notes currently stored on disk?  (I would like to implement my own backup for the time being)

**Comment by Rokt33r** [comment]
Sorry for late answer. I thought I've already answered this issue because I've been asked a lot of same questions.

Btw, You can find the stored data here

OS X
```
/Users/$USER_NAME$/Library/Application Support/boost/local.json
```

Windows
```
C:\Users\$USER_NAME$\AppData\Roaming\boost\local.json
```

And also check #29 if you want to know further changes.
