### ISSUE TITLE
Can I backup all my notes in case I need to format/clean my hard-disk?

### ISSUE THREAD

**Issue by omarojo** [BoostIO/boost-app-discussions#57]
I format my computer very often. Is there a way to backup all notes so once I have a clearn install of my O.S I can load all my notes again ?

**Comment by Rokt33r** [comment]
Of course, it can! 

Current version stores data to this JSON file.

OS X

```
/Users/$USER_NAME$/Library/Application Support/boost/local.json
```

Windows

```
C:\Users\$USER_NAME$\AppData\Roaming\boost\local.json
```

And check here #29 for the future changes.
