### ISSUE TITLE
About apis/xxxxx

### ISSUE THREAD

**Issue by dojineko** [BoostIO/boost-app-discussions#60]
`apis/activity` について質問です。
おそらくBoostNoteの利用状況を送信するものだと思うのですが、
具体的に何を送信しているのかお教えいただくことは可能でしょうか？

下記のAPIについては名前からなんとなくイメージがついたのですが…

- `apis/inquiry`
    - Contact Form を送信する API
- `apis/share`
    - b00st.io/share/***** に投稿するAPI 

ちなみに、これらのAPIを叩きたいとかではなくて、
自分の安心のため何をしているのか知りたいというような意図になります。

**Comment by Rokt33r** [comment]
シェア・投稿・削除などのボタンのクリック数、(シンタクスごとの)記事の数を収集しています。
アプリに新しい機能を追加した時にそれが正しい解決策であるのかの仮設検証をするための部分です。

詳しい情報は次のようになります。

実際に収集されるデータの例です。
```
{
  "ARTICLE_CREATE":1,
  "FOLDER_COUNT":2,
  "ARTICLE_COUNT":3,
  "CLIENT_VERSION":"0.5.4",
  "SYNTAX_COUNT":{"markdown":3},
  "ARTICLE_UPDATE":12,
  "ARTICLE_UPDATE_BY_SYNTAX":{"markdown":12}
}
```

ユーザの特定はSha keyをGitのようにアプリから発行して行っています。
```
f26e9b0ed7e33c146c8e060da33af284e6e6641b
```

**Comment by dojineko** [comment]
機能改善の効果測定に使うということですね ご回答有り難うございました！ :bow:

**Comment by Rokt33r** [comment]
また気になることがあったらいつでも聞いてください！:dancer:
