### ISSUE TITLE
Linux app

### ISSUE THREAD

**Issue by germanocorrea** [BoostIO/boost-app-discussions#61]
I don't get how hard it's to build Boost for linux, since electron is multiplataform. What's the big deal with it?
When is going to be launched? You have any idea?

It seems a great app, but I don't use OS X, neither Windows.... 

Thanks

**Comment by Rokt33r** [comment]
There are two problems

1. Auto update
2. Finder popup

These must be developed and tested in Linux. But, currently, I have no PC using Linux.

But, I think I can give you a build for Linux which removed 'auto update' and 'finder popup'.

**Comment by germanocorrea** [comment]
I think probably I can live without auto update and finder popup while you don't launch it for linux.

Thanks!

**Comment by Rokt33r** [comment]
Okay, I'll give you a download link and instruction here tomorrow! :smile:

**Comment by germanocorrea** [comment]
Thanks a lot! :smile:

**Comment by Rokt33r** [comment]
Sorry for late update. You can download from the link below.
https://www.dropbox.com/s/enwowfaia3jg003/Boostnote-linux-x64.zip?dl=0

**Comment by germanocorrea** [comment]
No problem... Thanks!

**Comment by gromain** [comment]
This is great! I was waiting for the linux version to try (and maybe adopt!) this app!

**Comment by gromain** [comment]
Just tried it, I love it!

I just wrote a simple `/usr/share/applications/boosnote.desktop` file after installing the program inside `/home/username/bin/boostnote` and grabbing `logo.png` from your homepage.
Here it goes:
```
[Desktop Entry]
Type=Application
Version=0.5.4
Name=Boostnote
Comment=Note-taking application for programmers
Icon=/home/username/bin/boostnote/logo.png
Exec=/home/username/bin/boostnote/Boostnote
Path=/home/username/bin/boostnote
Categories=Development;
Name[en_US]=Boostnote
```

Be careful to change _username_ to your real username when trying it!

**Comment by Rokt33r** [comment]
@gromain Wow.... I'm really sorry for making you wait!! I'm so grateful. :smile:

**Comment by gromain** [comment]
Hey, no worries! I stumble on the website again just today, so it wasn't really big trouble! I love how the app is doing! Can't wait to see what's ahead!

**Comment by gromain** [comment]
Also, once there is a proper (real) package for Linux, I'll be happy to act as a maintainer for the Arch User Repository (user-contributed repository for Arch Linux users)! Let's stay in touch!

**Comment by Rokt33r** [comment]
It is so glad to hear that! Are you using Arch Linux currently?

**Comment by gromain** [comment]
Yes, a derivative called Manjaro. But they are using the same repository for user-contributed packages.

**Comment by gromain** [comment]
What version of Electron are you using? I have a problem where I don't have the icon in the taskbar. I believe it's linked to electron as I have the same problem with the Rocket.chat application.

**Comment by Rokt33r** [comment]
It is using v0.35.4.

**Comment by gromain** [comment]
Okay, thank you! I'll bring up the problem to the Electron team!

**Comment by germanocorrea** [comment]
I'm Arch Linux user too (not Manjaro), and I'm heading to learn how to contribute to AUR, because there are some apps I would like to put there. If you need help with something, just send me an email.

**Comment by gromain** [comment]
For the next release, it'll be nice to upgrade to the latest (0.36.9) electron version, as it fixes a very nasty bug for Linux users ( https://github.com/atom/electron/issues/4513 ).
That would be awesome!

**Comment by Rokt33r** [comment]
@gromain 
It should be. I'll re-upload the upgraded version this weekend.
It might be along with publishing the OSS repository.

**Comment by Rokt33r** [comment]
Im sorry to be late update.. I'll finish it till this Tuesday!!

**Comment by Rokt33r** [comment]
@gromain 
Sorry for being late again. I'm still on working now. You can check the progress here. https://github.com/BoostIO/Boostnote

**Comment by gromain** [comment]
No problems! Don't worry!

I'll try to check it out today and build it to see how it goes! I'll let you know!

**Comment by Rokt33r** [comment]
@gromain 
I re-uploaded it to the same URL. You can download it now! 
https://www.dropbox.com/s/enwowfaia3jg003/Boostnote-linux-x64.zip?dl=0

And, you can find this codes in `linux` branch of the repository.(from 0.35 to 0.36, some apis of BrowserWindow are changed. I applied the changes to this branch!)
https://github.com/BoostIO/Boostnote/tree/linux

**Comment by Rokt33r** [comment]
@gromain  @germanocorrea 
Which desktop env should I use? I'm going to try [xfce](http://www.xfce.org/). If there are other better options, please tell me.

----
Let's continue this issue on OSS repository.
https://github.com/BoostIO/Boostnote/issues/5
