### ISSUE TITLE
Possibility to resize the two vertical bars on the left

### ISSUE THREAD

**Issue by gromain** [BoostIO/boost-app-discussions#66]
It would be nice to be able to size down/up the two bars on the left (the one with the folders, and the one with the content of them). They use a lot of space, especially since I'm using Boostnote on half my screen.

Also, maybe a button to collapse each bar would be great!

**Comment by Rokt33r** [comment]
It should be! 
This is a duplicated issue. But don't worry about it. I'll clean up all issues on Saturday after announce about OSS.

**Comment by gromain** [comment]
Sorry, I didn't saw it! :D
