### ISSUE TITLE
Checkbox Markdown support

### ISSUE THREAD

**Issue by kakajika** [BoostIO/boost-app-discussions#67]
Hi, I like Boostnote.
In Github Flavored Markdown, we can write checkbox for tasklists like this.
```
- [x] Foo
- [ ] Bar
- [ ] Baz
```
I also want to use it in Boost.
Thanks.

**Comment by Rokt33r** [comment]
Sorry for the late answer. It is already available.
<img width="211" alt="screen shot 2016-03-07 at 0 12 51" src="https://cloud.githubusercontent.com/assets/5865853/13554997/5cf59c24-e3f9-11e5-9ffb-570372f3b449.png">
.

**Comment by kakajika** [comment]
Oh, I'm sorry...
I seem to have been using beta-version of this App.
Thank you for your reply.

**Comment by Rokt33r** [comment]
@kakajika It's okay! Don't hesitate to ask. :+1:
