### ISSUE TITLE
[UI request] Wrapping long line of tags

### ISSUE THREAD

**Issue by baudren** [BoostIO/boost-app-discussions#69]
When being verbose with tags, the following happens: there is a scrollbar to accommodate all the tags, but the right-most ones are hidden. Could it be possible to wrapping the line instead?

![screenshot from 2016-03-11 23-09-14](https://cloud.githubusercontent.com/assets/3526120/13717024/0baa8e6c-e7df-11e5-9cb4-f096fa9a6043.png)

**Comment by Rokt33r** [comment]
Oh... I've just realized that It would be better... Thanks again.
I'll close it after shipped to the next release.

**Comment by baudren** [comment]
Great, thanks. Will the next release be available on Linux directly? I downloaded the current one from one of the threads here - should I continue to watch it for getting the new version?

**Comment by Rokt33r** [comment]
Yes, I will.
The only problem is that I need to learn how to make auto-update possible. Till then, I'll upload Linux app to [the releases page of Official Repository](https://github.com/BoostIO/Boostnote/releases).

**Comment by baudren** [comment]
Ok, great. Thanks for such a nice tool, and good luck with it!

**Comment by Rokt33r** [comment]
It also will be released tomorrow.
Watch here! https://trello.com/b/wJlinZJx/boostnote-todo-list

**Comment by Rokt33r** [comment]
Shipped!
You can download it from here!
https://github.com/BoostIO/Boostnote/releases/tag/v0.5.5-pre

**Comment by baudren** [comment]
Awesome, thanks for the reactivity!
