### ISSUE TITLE
Planned features / 計画されている機能 / 계획되어있는 기능들

### ISSUE THREAD

**Issue by Rokt33r** [BoostIO/boost-app-discussions#7]
## Post management with File system

Saving posts in a selected folder will be available. You will be able to sync your posts with Dropbox or Google drive.

## Post management with Git

Managing with Git will be available. Some users who don't know how to use Git would also use it easily because Boost app will automatically control Git. And we will give you an option using Github repository instead of Dropbox.

## Respect for your style

You will be able to switch any markdown parser and code editor you want.

These are candidates. Feel free to tell us if you want other options! We will accept your opinion gladly.

Type|Candidates
---|---
Code editor|Ace editor*, Codemirror
Markdown parser|Markdown-it*, Mdast

> `*` :  Currently using

And also, you will be able to change every short-cut keys in Boost app.
(We will provide some presets like Emacs and Vim)

Our team just realized these are crucial things for Programmer. We don't want to bother you these trivial things.

---
> 日本語

## ファイルベースでのポスト管理

フォルダーを指定しておいて、ポストを保存するようにします。DropboxやGoogle driveを使ったら簡単に同期化できるようにするつもりです。

## Gitベースでのポスト管理

保存されているファイルをGitで管理します。Boost アプリが自動でGitを制御するためGitの使い方がしらなくても使えます。そして、GithubなどのGit repositoryもDropboxの代わりに使えるようにするよていです。

## より自由に

Markdown parserやCode editorを自由自在に変えられるようにするつもりです。

以下は候補です。もし他にも追加してほしいものがあったら気軽に聞いてください。

Type|Candidates
---|---
Code editor|Ace editor*, Codemirror
Markdown parser|Markdown-it*, Mdast

> `*` :  現在使用中

そして、BoostのすべてのShort-cut keyを変えることができるようになります。
(EmacsとVim向けのキーボードPresetも提供する予定です。)

プログラマーにおいてこういうのが重大であるのを遅く気づきました。私たちはこういう細かいことで苦しむことを望んでいないです。もっと頑張ります！

---
> 한국어

## 파일 베이스로 포스트 관리

폴더를 지정해두어 포스트를 저장 할 수 있게 합니다. Dropbox나 Google drive를 사용해 간편하게 동기화 하실 수 있을겁니다!

## Git베이스로 포스트 관리

저장된 파일들을 Git으로 관리합니다. Boost 앱이 자동적으로 Git을 제어하기 때문에 Git을 모르는 유저라도 쓸 수 있을것입니다. 또한 여러분의 Github등의 Git repository도 Dropbox 대신에 사용 할 수 있게 하려 합니다.

## 보다 자유롭게

Markdown parser와 코드에디터를 자유자재로 바꿀 수 있게 하려합니다.

이하는 후보입니다. 이것들 이외에도 추가했으면 하는 것들이 있으면 언제든 말씀해주세요.

Type|Candidates
---|---
Code editor|Ace editor*, Codemirror
Markdown parser|Markdown-it*, Mdast

> `*` :  현재사용중

그리고 Boost의 모든 숏컷키를 바꿀수있게도 하려합니다.
(Emacs와 Vim에 맞춰진 프리셋도 제공할 계획입니다.)

프로그래머에 대해 이러한 문제가 중요하다는걸 늦게서야 알아챘습니다. 저흰 이런 자잘한 문제들이 여러분들의 작업을 방해하지 않았으면 합니다. 더 열심히 노력하겠습니다!

**Comment by Rokt33r** [comment]
added(2015/11/30) : Customization

**Comment by Rokt33r** [comment]
modified (2015/12/1) : Marked -> Mdast
> Marked seems to be maintain no longer.

**Comment by two-hats** [comment]
Chromeなどブラウザの拡張機能版もあるといいですね。データが同期してくれたなお嬉しいです。

**Comment by Rokt33r** [comment]
@two-hats おお！それもいいですね！意見ありがとうございます！
