### ISSUE TITLE
share all contents with some PCs

### ISSUE THREAD

**Issue by yoshimaa** [BoostIO/boost-app-discussions#76]
can i share all contents with some PCs?
i know we can share  contents, but how can i all?
it doesn't mean to do realtime sync.

thanks:)

**Comment by Rokt33r** [comment]
Boostnote is currently storing all stuff in a single json file.
You can do it by just moving the file.

See #29 to check the location of the file.
And, Slightly wait a little more. v0.6 will be released soon.
