### ISSUE TITLE
Account name on the sidebar

### ISSUE THREAD

**Issue by ystkme** [BoostIO/boost-app-discussions#8]
I have a request to improve this app which is about the user account name on its sidebar.

Reasons to request:

- It overlaps with "Preferences" button and looks bad if account name is too long.
- Some might not want their account name to be public so they can get bothered trying to upload screenshots.

Ideas to improve:

- No account name on sidebar(ex. Boost logo instead)
- Prepare an option to change the text

---

サイドバーに表示されているユーザアカウント名について、改善してほしいと思うところがあります。

理由としては、

- アカウント名の文字数が多いと"Preferences"のボタンと重なってしまって見た目がよくない
- ブログなどにスクリーンショットをアップする時に困るケースがあるかも

です。改善案としては、

1. アカウント名を表示しない（例えば、代わりにboostロゴを表示する）
2. 表示するテキストを選択するオプションを用意する

などがあると思います。検討してもらえると嬉しいです。

**Comment by Rokt33r** [comment]
意見ありがとうございます。
User名を自由にせっていできるようにします。
そして、他の情報に切り替えたりしたらいいかなと思いますけど、ちょっと考えてみます。

**Comment by Rokt33r** [comment]
v0.4.4から変えられるようになりましたので閉じます！
